### ISSUE TITLE
Question: Is it possible to change the clip directory generated in the subcut?

### ISSUE THREAD

**Issue by diegopds83** [kelciour/mpv-scripts#13]
I only have this doubt: Currently, the clip generated is saved in my  `~/` directory.

Is it possible to define another directory so that it is saved? Thank you very much in advance.

The script is working very well! Congratulations!

**Comment by kelciour** [comment]
To save the video clip without subtitles into a different folder, try to set or replace `working-directory` with a different path either in the line 313 or in the line 339.

`https://github.com/kelciour/mpv-scripts/blob/9a5cda4fc8f0896cec27dca60a32251009c0e9c5/sub-cut.lua#L313`

https://github.com/kelciour/mpv-scripts/blob/9a5cda4fc8f0896cec27dca60a32251009c0e9c5/sub-cut.lua#L313

`https://github.com/kelciour/mpv-scripts/blob/9a5cda4fc8f0896cec27dca60a32251009c0e9c5/sub-cut.lua#L339`

https://github.com/kelciour/mpv-scripts/blob/9a5cda4fc8f0896cec27dca60a32251009c0e9c5/sub-cut.lua#L339
