### ISSUE TITLE
sub-cut.lua and youtube links

### ISSUE THREAD

**Issue by Osteri** [kelciour/mpv-scripts#2]
First of all, thank you for your awesome work. I use sub-cut.lua and it works perfectly – except when dealing with youtube links. 

Right now, when I try to cut youtube videos, the sub-cut.lua plugin gives the following error:
`/home/user/watch?v=WOfmnbU5S5o: No such file or directory`
when opened with
`mpv https://www.youtube.com/watch?v=WOfmnbU5S5o`
and trying to cut the video.

It obviously points to a non-existing file, as it is a not known use case for the plugin.

It would be awesome if you were able to cut youtube videos on the fly. I have no idea how hard this is to implement, but it would be nice-to-have feature.

You would have to know where and how the cache is layed, and from there, try to figure out which parts to use.

Somewhat related links on this issue:
https://mpv.io/manual/master/#options-cache-file
https://github.com/antoniy/mpv-youtube-dl-binding/issues/32
https://github.com/rg3/youtube-dl/issues/622

**Comment by kelciour** [comment]
Thank you. That's great! I'm happy :).

About the issue. At first, I thought it would be beyond my current abilities, but after it struck me that in this case I can rely entirely on mpv to encode video and audio as I did recently with [mpv2anki](https://ankiweb.net/shared/info/1213145732) add-on.

So, here's an updated version of this script - https://github.com/kelciour/mpv-scripts/blob/development/sub-cut.lua
I've updated the header, added new replay hotkeys and changed previous hotkeys a little.

**Comment by Osteri** [comment]
Wow. I wasn't excepting this. Thank you very much for your work!

Works perfectly, except it gives:
```
[ffmpeg] NULL: Invalid NAL unit size (16744 > 7939).
[ffmpeg] NULL: missing picture in access unit with size 7943
```
when saving a video file. 

But it works, so whatever I guess.
