### ISSUE TITLE
Script to speed up sections without subtitle

### ISSUE THREAD

**Issue by jgandert** [kelciour/mpv-scripts#6]
Not sure if you would be interested in creating something like that, but I love the idea of a script that would fast forward (let's say, a configurable 200% increase of the current speed) while there are no subtitles, and would immediately slow down to the previous speed once there are subtitles again.

**Comment by kelciour** [comment]
I haven't tried them, but a while ago I came across something similar.

> This is a lua script for the mpv media player. The purpose of this script is to speed up the video if no subtitles are visible for a certain amount of (user configurable) time. It is inspired by the [speed-between-subs](https://gist.github.com/bitingsock/47c5ba6466c63c68bcf991dd376f1d18) script.

https://github.com/zenyd/mpv-scripts

**Comment by jgandert** [comment]
Thank you! That's exactly what I was looking for!
